apiVersion: v1
appVersion: 'RStudio: 4.1.2'
description: RStudio with Auth0 authentication proxy
icon: https://avatars3.githubusercontent.com/u/8361145?s=200&v=4?sanitize=true
maintainers:
- name: ministryofjustice
name: rstudio
version: 4.2.1
