# permissions for end users to view airflows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: airflow-viewer-role
rules:
- apiGroups:
  - tools.analytical-platform.justice.gov.uk
  resources:
  - airflows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tools.analytical-platform.justice.gov.uk
  resources:
  - airflows/status
  verbs:
  - get
