---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ap-tools.tools
  resources:
  - tools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ap-tools.tools
  resources:
  - tools/finalizers
  verbs:
  - update
- apiGroups:
  - ap-tools.tools
  resources:
  - tools/status
  verbs:
  - get
  - patch
  - update
