# permissions for end users to edit usertools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: usertools-editor-role
rules:
- apiGroups:
  - ap-tools.tools
  resources:
  - usertools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ap-tools.tools
  resources:
  - usertools/status
  verbs:
  - get
