# permissions for end users to view usertools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: usertools-viewer-role
rules:
- apiGroups:
  - ap-tools.tools
  resources:
  - usertools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ap-tools.tools
  resources:
  - usertools/status
  verbs:
  - get
