apiVersion: tool.analytical-platform.justice/v1alpha1
kind: Jupyterlabs
metadata:
  name: jupyterlabs-sample
spec:
  # Default values copied from <project_dir>/helm-charts/jupyter-lab/values.yaml
  Username: test
  aws:
    accountID: "593291632749"
    defaultRegion: eu-west-1
    iamRole: ""
  cookie_secret: ""
  jupyter:
    containerPort: 8888
    image: 593291632749.dkr.ecr.eu-west-1.amazonaws.com/allspark-notebook
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 1.5
        memory: 12Gi
      requests:
        cpu: 1.5
        memory: 12Gi
    tag: v2.1.0-rc1
  proxy:
    auth0:
      clientId: ""
      clientSecret: ""
      domain: AUTH0_USER.eu.auth0.com
      logoutUrl: https://controlpanel.services.alpha.mojanalytics.xyz/
    image:
      pullPolicy: IfNotPresent
      repository: 593291632749.dkr.ecr.eu-west-1.amazonaws.com/nginx-proxy-jupyter
      tag: 0.0.1
    port: 3000
    resources:
      limits:
        cpu: 1
        memory: 128Mi
      requests:
        cpu: 0.5
        memory: 128Mi
  service:
    port: 80
  toolsDomain: tools.example.com
  
  
